Db changes in files
oona988/snowledge pull request #16
Opened 2021-10-28 11:07 UTC by Abdullaharifbhatti

Whoever pulls the port number need to change back again to 3306 in vagrant file

2021-10-30 19:16 UTC, oona988 commented
Some of these database changes are also needed in database routers. So that API requests are possible to create. For example in src/routers/api.js and src/routers/objectRouters/updates.js.

For example row 35 in updates.js file:

database.query("INSERT INTO Paivitykset(Tekija, Segmentti, Lumilaatu, Teksti, Aika) VALUES(?, ?, ?, ?, NOW())",

2021-10-30 19:17 UTC, oona988 commented
Also is it possible to store multiple snowtypes to database?

2021-11-04 11:14 UTC, oona988 commented
Some errors appear when creating database, seems that there is some mysql syntax problem: 

default: ERROR 1064 (42000) at line 26: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'CONSTRAINT tunniste PRIMARY KEY (Aika, Segmentti)
    default: )' at line 14
    default: ERROR 1136 (21S01) at line 8: Column count doesn't match value count at row 1
    default: ERROR 1146 (42S02) at line 1: Table 'pallas.Koordinaatit' doesn't exist
    default: ERROR 1146 (42S02) at line 1: Table 'pallas.Alalumilaadut' doesn't exist

2021-11-04 11:18 UTC, oona988 commented
> Some errors appear when creating database, seems that there is some mysql syntax problem:
> 
> default: ERROR 1064 (42000) at line 26: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'CONSTRAINT tunniste PRIMARY KEY (Aika, Segmentti) default: )' at line 14 default: ERROR 1136 (21S01) at line 8: Column count doesn't match value count at row 1 default: ERROR 1146 (42S02) at line 1: Table 'pallas.Koordinaatit' doesn't exist default: ERROR 1146 (42S02) at line 1: Table 'pallas.Alalumilaadut' doesn't exist

2021-11-04 11:51 UTC, oona988 commented on src/sql/luonnit.sql
> +    Lumilaatu_ID bigint(20) unsigned,
There are Lumilaatu and Lumilaatu_ID in table Paivitykset, and both of these are referring to snowtype ID.

2021-11-04 11:58 UTC, oona988 commented on src/sql/Alalumilaadut.sql
> +(17,'kantoja',10,NULL);
Would be good to capitalize all of these sub snowtype names

2021-11-08 14:44 UTC, oona988 commented
There seems to be still some errors when creating the database:

default: ERROR 1215 (HY000) at line 26: Cannot add foreign key constraint
default: ERROR 1146 (42S02) at line 1: Table 'pallas.Koordinaatit' doesn't exist
default: ERROR 1146 (42S02) at line 1: Table 'pallas.Alalumilaadut' doesn't exist

2021-11-15 21:00 UTC, collandk approved these changes
Everything is working in Vagrant as expected now

2021-11-16 08:17 UTC, collandk requested changes
Whoops, cancelling the approval. Oonas comment was forgotten to fix:
There are Lumilaatu and Lumilaatu_ID in table Paivitykset, and both of these are referring to snowtype ID.

2021-11-16 20:57 UTC, collandk approved these changes

2021-11-16 21:01 UTC, collandk commented
All fixes are now done and to us everything seems to be working fine!  It would be good for someone else to verify that all tables are created successfully with all the wanted initial data. The person who approves this change can also merge it.

2021-11-17 17:49 UTC, emilcalonius approved these changes
Everything seemed to work fine for me so I am approving these changes.

2021-11-17 17:50 UTC, merged